name: "Test Post to PR"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: env
    - run: npm ci
    - run: npm test | tee unit_test_result.txt
    - name: "Post to PR"
      uses: ./
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        comment_url: ${{ github.event.pull_request.comments_url }}
        post_to_pr_definition: |
          [
            {
              "message_file": "./unit_test_result.txt",
              "title": "Unit Test",
              "modifier": "grep -v '::debug::'"
            }
          ]
      if: github.event_name == 'pull_request'